### ISSUE TITLE
Add simple argument processing

### ISSUE THREAD

**Issue by AnthonyMBonafide** [NightyKnight/learn-java#3]
Add some simple logic which prints all the arguments passed to the application. Add the logic to the main function in the `App.java` here: 

https://github.com/NightyKnight/learn-java/blob/9c004943d7a2386e554a9c676ef3310a29302158/src/main/java/education/App.java#L11

In Java, the arguments supplied to the program are available in the `args` variable which you can see here: 

https://github.com/NightyKnight/learn-java/blob/9c004943d7a2386e554a9c676ef3310a29302158/src/main/java/education/App.java#L9

The `args` variable is an `array` of Strings. You can read about arrays in Java [here](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/arrays.html). To print all of the `args` simply use a `for-loop` to iterate over all of the values.

NOTE:
Arrays in Java are 0 indexed, which means the first element of the array is 0 and the last is whatever the length of the array is minus 1. The amount of elements in the array is referred to as the `length`. For example, given the following array [a,b,c,d]. The array is of `length` 4. The following are the elements and their index:

a - 0
b - 1
c - 2
d - 3

To access an element of an array simply use the variable name and the index within square brackets. For example, in our main function we could get the first argument like so:
`args[0]`
You can use access the length property available on arrays like so `args.length`

To test this you will need to update the `Run configuration` in your IDE. For IntelliJ, open the [Edit configurations](https://www.jetbrains.com/help/idea/run-debug-configuration.html) option at the top right of the IDE and in the `Program arguments` section add a your arguments. Arguments are separated by spaces. For example `one two three`

**Comment by AnthonyMBonafide** [comment]
Also, try to use the git client. Uploading via the browser will cause you problems in the future

**Comment by NightyKnight** [comment]
The main function iterates through the array and prints out the results. I also uploaded from the git bash client using my SSH key.
